version: 2

jobs:
  # deployという名前のjobの定義を以下記述
  deploy:
    # circleciが検証用に用意するコンテナ内でのソースコードの置き場
    working_directory: ~/app

    # circleciが建てるdocker imageの種類
    docker:
      - image: circleci/node:14

    # deployというjobを行うためにcircleciのdocker内で動作させるコマンド
    steps:
      - checkout
      - setup_remote_docker
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # enable docker
      - run:
          name: build and deploy cdk
          working_directory: ~/app/cdk
          command: |
            npm install
            npm run cdk deploy
      # - run:
      #     name: Deploying
      #     command: eb deploy [created-my-env-name]

workflows:
  version: 2
  build:
    jobs:
      # name of job
      - deploy:
          filters:
            branches:
              only:
                - main
